"""

Revision ID: 8f2fc156b3bb
Revises: ecd62863c9d0
Create Date: 2025-11-13 14:11:13.445064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f2fc156b3bb'
down_revision: Union[str, Sequence[str], None] = 'ecd62863c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_preferences_id'), 'global_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_global_preferences_user_id'), 'global_preferences', ['user_id'], unique=False)
    op.create_table('route_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('from_latitude', sa.Float(), nullable=False),
    sa.Column('from_longitude', sa.Float(), nullable=False),
    sa.Column('to_latitude', sa.Float(), nullable=False),
    sa.Column('to_longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_preferences_id'), 'route_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_route_preferences_user_id'), 'route_preferences', ['user_id'], unique=False)
    op.drop_index(op.f('ix_preference_id'), table_name='preference')
    op.drop_index(op.f('ix_preference_user_id'), table_name='preference')
    op.drop_table('preference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('preference_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('preference_pkey'))
    )
    op.create_index(op.f('ix_preference_user_id'), 'preference', ['user_id'], unique=False)
    op.create_index(op.f('ix_preference_id'), 'preference', ['id'], unique=False)
    op.drop_index(op.f('ix_route_preferences_user_id'), table_name='route_preferences')
    op.drop_index(op.f('ix_route_preferences_id'), table_name='route_preferences')
    op.drop_table('route_preferences')
    op.drop_index(op.f('ix_global_preferences_user_id'), table_name='global_preferences')
    op.drop_index(op.f('ix_global_preferences_id'), table_name='global_preferences')
    op.drop_table('global_preferences')
    # ### end Alembic commands ###
